services:
  slope64-api:
    build: .
    runtime: sysbox-runc
    ports:
      - "0.0.0.0:8110:8110"
    env_file:
      - .env
    volumes:
      - ./static:/app/static:ro
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:

networks:
  default:
    name: slope64-internal
